using System.Reflection;
using System.IO;
using System;
using UnityEngine;
using System.Linq;
using System.Collections.Generic;
using UnityEditor;

namespace Ami.Extension.Reflection
{
#if BroAudio_DevOnly_GeneratedCodeSample
    public interface IAudioSourceModifierSample
    {
        float volume { set; }
    }

    public class AudioSourceModifierSample : BroModifier, IAudioSourceModifierSample
    {
        private AudioSource _audioSource;

        public const float Default_Volume = 1f;
        private bool _hasVolumeResetAction = false;
        public float volume
        {
            set
            {
                if (!_hasVolumeResetAction)
                {
                    AddResetAction(() => _audioSource.volume = Default_Volume);
                    _hasVolumeResetAction = true;
                }

                _audioSource.volume = value;
            }
        }
    }
#endif

    public static class AudioSourceProxyGenerator
    {
        [MenuItem("Tools/BroAudio/Generate Audio Source Proxy")]
        public static void Generate()
        {
            GenerateScriptSetter.Parameters parameters = new GenerateScriptSetter.Parameters()
            {
                Namespace = "Ami.Extension.Reflection",
                ScriptName = "AudioSourceProxy",
                Path = Path.GetFullPath("Assets/BroAudio/Core/Scripts/Player/AutoGeneratedCode"),
                Usings = new string[] { "System", "UnityEngine", "UnityEngine.Audio" },
            };

            GenerateScriptSetter.GenerateModifierCode<AudioSource>(parameters);
        }
    }

    public static class GenerateScriptSetter
    {
        public const string Title = "// Auto-generated code";
        public const string FourSpaces = "    ";
        public struct Parameters
        {
            public string Namespace;
            public string ScriptName;
            public string Path;
            public string[] Usings;
            public bool IncludeBaseTypeMembers;
        }

        public struct AutoBraces : IDisposable
        {
            private StreamWriter _writer;
            public AutoBraces(string text, StreamWriter writer)
            {
                _writer = writer;
                if (string.IsNullOrEmpty(text))
                {
                    _writer = null;
                    return;
                }

                writer.WriteLine(text);
                writer.WriteLine("{");
            }

            public void Dispose()
            {
                _writer?.WriteLine("}");
            }
        }

        public static void GenerateModifierCode<T>(Parameters parameters, BindingFlags bindingFlags = BindingFlags.Public | BindingFlags.Instance)
        {
            Type type = typeof(T);
            MemberInfo[] members = type.GetMembers(bindingFlags);

            if (members == null || members.Length == 0)
            {
                Debug.LogError($"No valid members in {type}, BindingFlags:{bindingFlags}");
                return;
            }

            if (!Directory.Exists(parameters.Path))
            {
                Debug.LogError($"Path:{parameters.Path} not exist!");
                return;
            }

            CreateModifierInterface<T>(parameters, members);
            //CreateModifierClass<T>(parameters, members);
            AssetDatabase.Refresh();
        }

        private static void CreateModifierInterface<T>(Parameters parameters, MemberInfo[] members)
        {
            string interfaceName = "I" + parameters.ScriptName;
            using (var file = File.CreateText(Path.Combine(parameters.Path, interfaceName + ".cs")))
            {
                file.WriteLine(Title);
                file.WriteUsings(parameters.Usings);
                file.WriteLine();

                string indent = string.Empty;
                using ( file.WriteBraces("namespace " + parameters.Namespace))
                {
                    indent += FourSpaces;
                    using (file.WriteBraces(indent + "public interface " + interfaceName))
                    {
                        indent += FourSpaces;
                        var filteredMembers = members
                            .Where(x => x.MemberType == MemberTypes.Property)
                            .Where(x => !parameters.IncludeBaseTypeMembers && x.DeclaringType == typeof(T));

                        foreach (var member in filteredMembers)
                        {
                            if (member is PropertyInfo property)
                            {
                                file.WriteLine(indent + string.Format("{0} {1} {{ set; }}", property.PropertyType.Name, property.Name));
                            }
                        }
                    }
                }
            }
        }

        private static void CreateModifierClass<T>(Parameters parameters, MemberInfo[] members)
        {
            using (var file = File.CreateText(Path.Combine(parameters.Path, parameters.ScriptName + ".cs")))
            {
                file.WriteLine(Title);
                file.WriteUsings(parameters.Usings);

                using (file.WriteBraces(parameters.Namespace))
                {
                    using (file.WriteBraces("public static class " + parameters.ScriptName))
                    {
                        var filteredMembers = members
                            .Where(x => x.MemberType == MemberTypes.Field || x.MemberType == MemberTypes.Property)
                            .Where(x => !parameters.IncludeBaseTypeMembers && x.DeclaringType == typeof(T));

                        foreach (var member in filteredMembers)
                        {
                            file.WriteLine($"{member.ReflectedType}");
                        }
                    }
                }
            }
        }

        private static AutoBraces WriteBraces(this StreamWriter writer, string text)
        {
            return new AutoBraces(text, writer);
        }

        private static void WriteUsings(this StreamWriter writer, string[] usings)
        {
            if (usings != null)
            {
                foreach (var usage in usings)
                {
                    writer.WriteLine($"using {usage};");
                }
            }
        }
    }
}
