#if BroAudio_DevOnly
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using Ami.BroAudio.Tools;
using UnityEditor;
using UnityEngine;

namespace Ami.Extension.Reflection
{
    public static class AudioSourceProxyGenerator
    {
        [MenuItem(BroName.MenuItem_BroAudio + "Others/Generate Audio Source Proxy")]
        public static void GenerateAudioSourceProxy()
        {
            ProxyModifierCodeGenerator.Parameters parameters = new ProxyModifierCodeGenerator.Parameters()
            {
                Namespace = "Ami.Extension",
                ScriptName = "AudioSourceProxy",
                Path = GetPackageRelativePath("Core/Scripts/Player/AutoGeneratedCode"),
                ClassImplementation = nameof(IDisposable),
                Usings = new List<string> { nameof(UnityEngine), nameof(UnityEngine) + ".Audio" },
                MethodNameList = new string[] 
                { 
                    nameof(AudioSource.GetCustomCurve), nameof(AudioSource.SetCustomCurve),
                    nameof(AudioSource.GetAmbisonicDecoderFloat), nameof(AudioSource.SetAmbisonicDecoderFloat),
                    nameof(AudioSource.GetSpatializerFloat), nameof(AudioSource.SetSpatializerFloat),
            };

            ProxyModifierCodeGenerator.GenerateModifierCode<AudioSource>(parameters, needEmpty: true, orderBy: ClipPropertyAtLast);
        }

        private static int ClipPropertyAtLast(PropertyInfo x, PropertyInfo y)
        {
            bool xIsClip = x != null && x.Name == nameof(AudioSource.clip);
            bool yIsClip = y != null && y.Name == nameof(AudioSource.clip);

            if (xIsClip == yIsClip)
            {
                return 0;
            }
            return xIsClip ? 1 : -1;
        }
        
        [MenuItem(BroName.MenuItem_BroAudio + "Others/Generate Audio Effect Proxies")]
        public static void GenerateAudioEffectProxies()
        {
            ProxyModifierCodeGenerator.Parameters parameters = new ProxyModifierCodeGenerator.Parameters()
            {
                Namespace = "Ami.Extension",
                Path = GetPackageRelativePath("Core/Scripts/Player/AutoGeneratedCode/AudioEffects"),
                ClassImplementation = nameof(IAudioEffectModifier),
                IncludedBaseTypes = new List<Type> { typeof(Behaviour) },
                Usings = new List<string> { nameof(UnityEngine) },
                DependencyComponentTypes = new Type[] { typeof(AudioSource) },
            };

            Generate<AudioHighPassFilter>(nameof(AudioHighPassFilter));
            Generate<AudioLowPassFilter>(nameof(AudioLowPassFilter));
            Generate<AudioReverbFilter>(nameof(AudioReverbFilter));
            Generate<AudioDistortionFilter>(nameof(AudioDistortionFilter));
            Generate<AudioEchoFilter>(nameof(AudioEchoFilter));
            Generate<AudioChorusFilter>(nameof(AudioChorusFilter));


            void Generate<T>(string className) where T : Component
            {
                parameters.ScriptName = className + "Proxy";
                ProxyModifierCodeGenerator.GenerateModifierCode<T>(parameters, isEffectModifier: true);
            }
        }

        private static string GetPackageRelativePath(string relativePath)
        {
            // For UPM packages, we need to find the package root
            var packageInfo = UnityEditor.PackageManager.PackageInfo.FindForAssembly(typeof(AudioSourceProxyGenerator).Assembly);
            if (packageInfo != null && !string.IsNullOrEmpty(packageInfo.resolvedPath))
            {
                return System.IO.Path.Combine(packageInfo.resolvedPath, relativePath);
            }

            // Fallback for development (when package is in Packages folder)
            return System.IO.Path.GetFullPath("Assets/BroAudio/" + relativePath);
        }
    }
}
#endif